name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - uses: actions/checkout@v2
    - name: docker login
    - run : docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Container image
    - run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
    - name: Publish Docker image
    - run: docker push ${{ secrets.DOCKER_REPO }}
    
    
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
